# Generated by Django 5.2.8 on 2025-11-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionDeskCongestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_start', models.DateTimeField()),
                ('check_in_end', models.DateTimeField()),
                ('stand_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Reception_desk_congestion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QueueAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(default='Camera1', max_length=255)),
                ('sector', models.CharField(default='A', max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'queue_alerts',
            },
        ),
        migrations.CreateModel(
            name='QueueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(default='Camera2', max_length=255)),
                ('sector', models.CharField(default='A', max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('number_of_people', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'monitor_queueimage',
            },
        ),
    ]
